In [4]:
from scipy import linalg
import numpy as np

# Criptografia de Hill

## Chave criptografia

In [5]:
matrix_bonelord = np.array([[3,1,6,1],[1,2,1,1],[1,1,3,1],[4,6,1,1]])
matrix_bonelord

matrix_beholder = np.array([[1,1,1,1],[1,3,6,1],[1,1,4,1],[4,6,1,1]])
matrix_beholder

array([[1, 1, 1, 1],
       [1, 3, 6, 1],
       [1, 1, 4, 1],
       [4, 6, 1, 1]])

In [6]:
inv_matrix_bonelord = linalg.inv(matrix_bonelord)
inv_matrix_bonelord

inv_matrix_beholder = linalg.inv(matrix_beholder)
inv_matrix_beholder

array([[-8.88888889e-01, -8.33333333e-01,  1.38888889e+00,
         3.33333333e-01],
       [ 3.33333333e-01,  5.00000000e-01, -8.33333333e-01,
         1.38777878e-17],
       [-3.33333333e-01,  0.00000000e+00,  3.33333333e-01,
         0.00000000e+00],
       [ 1.88888889e+00,  3.33333333e-01, -8.88888889e-01,
        -3.33333333e-01]])

chave * mensagem_recebida = mensagem_decodificada

(4x4) * (4 x n_colunas) = (4x4)

In [7]:
candidatos_chave_criptografia = [matrix_bonelord, inv_matrix_bonelord, matrix_beholder, inv_matrix_beholder]

## Mensagem

A mensagem 'blinky' foi criptografada e recebemos ela em forma de números "1". Essa mensagem 'Tibia' foi primeiro transformada numa matriz e multiplicada pela chave de criptografia e obtemos os números "1" que foram dispostos em uma matriz.

Como requerimento, esses números devem se dispor em uma matriz com 4 linhas  (mesmo numero de colunas da matriz chave da criptografia), o número de colunas que essa matriz contem dependerá do tamanho de quantos algarismos a mensagem recebida "1" possui.

Nesse primeiro momento vamos testar 
n_colunas = 2, 
n_colunas = 3,
n_colunas = 4


também vamos supor que 1 seja preenchido na matriz de forma linear da direita para esquerda e outra alternativa de cima pra baixo.

In [8]:
msg = 'blinky'
numero_msg = 486486
numero_filler = 1

### Candidatos á matrizes codificada para mensagem 'Blinky'


## n_colunas = 1
matrix_msg1 =  np.array([[1],
                         [1],
                         [1],
                         [1]])


## n_colunas = 2
matrix_msg2 =  np.array([[1,1],
                         [1,1],
                         [1,1],
                         [1,1]])

## n_colunas = 3
matrix_msg3 =  np.array([[1,1,1],
                         [1,1,1],
                         [1,1,1],
                         [1,1,1]])


## n_colunas = 5
matrix_msg4 =  np.array([[1,1,1,1],
                         [1,1,1,1],
                         [1,1,1,1],
                         [1,1,1,1]])




In [9]:
candidatos_matriz_msg = [matrix_msg1,matrix_msg2,matrix_msg3,matrix_msg4]

# Candidatos a solução

## Inversa * Matriz Mensagem

A * X = B   
Onde A = Matriz chave  
X = Matriz equivalente á palavra 'Blinky'  
B = Matriz_msg  

In [10]:
candidatos_solucoes = []

for chave in candidatos_chave_criptografia:
    
    for matriz_msg in candidatos_matriz_msg:

        solucao = linalg.solve(chave,matriz_msg)

        candidatos_solucoes.append(solucao) 
        
candidatos_solucoes

[array([[ 0.],
        [-0.],
        [ 0.],
        [ 1.]]),
 array([[ 0.,  0.],
        [-0., -0.],
        [ 0.,  0.],
        [ 1.,  1.]]),
 array([[ 0.,  0.,  0.],
        [-0., -0., -0.],
        [ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]),
 array([[ 0.,  0.,  0.,  0.],
        [-0., -0., -0., -0.],
        [ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.]]),
 array([[11.],
        [ 5.],
        [ 6.],
        [12.]]),
 array([[11., 11.],
        [ 5.,  5.],
        [ 6.,  6.],
        [12., 12.]]),
 array([[11., 11., 11.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [12., 12., 12.]]),
 array([[11., 11., 11., 11.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [12., 12., 12., 12.]]),
 array([[0.],
        [0.],
        [0.],
        [1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0.,

## Arredondamento elementos para numero inteiro

In [11]:
def arredonda_elementos_para_inteiros(solucao):
    
    n_lin, n_col = solucao.shape
    ## Arredondando os numeros da matriz para inteiros
    for col in range(n_col):
        for lin in range(n_lin):
            solucao[lin][col] = round(solucao[lin][col])
    
    return solucao            

In [12]:
#solucao = candidatos_solucoes[0]
#solucao

In [13]:
#solucao = arredonda_elementos_para_inteiros(solucao)
#solucao

In [14]:
for num, solucao in enumerate(candidatos_solucoes):
    solucao = arredonda_elementos_para_inteiros(solucao)
    candidatos_solucoes[num] = solucao
candidatos_solucoes

[array([[0.],
        [0.],
        [0.],
        [1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]]),
 array([[11.],
        [ 5.],
        [ 6.],
        [12.]]),
 array([[11., 11.],
        [ 5.,  5.],
        [ 6.,  6.],
        [12., 12.]]),
 array([[11., 11., 11.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [12., 12., 12.]]),
 array([[11., 11., 11., 11.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [12., 12., 12., 12.]]),
 array([[0.],
        [0.],
        [0.],
        [1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
    

## Simplificação Matriz

Seta primeiro elemento = 1
e demais elementos positivos e multiplos de 26

In [15]:
def matriz_simplificada_b_igual_1(solucao):
    
    ## transforma todos os valores para que o primeiro valor seja = 1
    valor_b = solucao[0][0]
    solucao = solucao - valor_b + 1

    return solucao

In [16]:
#solucao = candidatos_solucoes[12]
#solucao

In [17]:
#matriz_simplificada_b_igual_1(solucao)

In [18]:
def matriz_simplificada(solucao):

    n_lin, n_col = solucao.shape
    
    ## Transforma elementos para numeros multiplos de 26
    for col in range(n_col):
        for lin in range(n_lin):
            
                valor = solucao[lin][col]
                x = valor//26
                i = valor-x*26
                solucao[lin][col] = i

    return solucao
    

In [19]:
#solucao = candidatos_solucoes[12]
#solucao

In [20]:
#solucao = matriz_simplificada_b_igual_1(solucao)
#solucao

In [21]:
#solucao = matriz_simplificada(solucao)
#solucao

In [22]:
for num, solucao in enumerate(candidatos_solucoes):
    solucao = matriz_simplificada_b_igual_1(solucao)
    solucao = matriz_simplificada(solucao)
    candidatos_solucoes[num] = solucao
candidatos_solucoes

[array([[1.],
        [1.],
        [1.],
        [2.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [2., 2.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]]),
 array([[ 1.],
        [21.],
        [22.],
        [ 2.]]),
 array([[ 1.,  1.],
        [21., 21.],
        [22., 22.],
        [ 2.,  2.]]),
 array([[ 1.,  1.,  1.],
        [21., 21., 21.],
        [22., 22., 22.],
        [ 2.,  2.,  2.]]),
 array([[ 1.,  1.,  1.,  1.],
        [21., 21., 21., 21.],
        [22., 22., 22., 22.],
        [ 2.,  2.,  2.,  2.]]),
 array([[1.],
        [1.],
        [1.],
        [2.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [2., 2.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
    

## Substituição

Sabemos que o primeiro elemento dessas matrizes é b, se b = primero elemento como ficam os outros elementos? eles correspondem a palavra 'blinky'??

In [36]:
alfabeto = ['s','t','u','v','w','x','y','z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s_']

def posicao_relacao_b(alfabeto, letra):
    pos = alfabeto.index(letra) + alfabeto.index('t') -1
    return pos

In [38]:
posicao_relacao_b(alfabeto,'a'), posicao_relacao_b(alfabeto,'b'), posicao_relacao_b(alfabeto,'c')

(8, 9, 10)

In [39]:
def dicionario_matriz_relacao_b(solucao):
    dicionario_solucao = {posicao_relacao_b(alfabeto,i):i for i in alfabeto}
    return dicionario_solucao

In [40]:
dicionario_global = dicionario_matriz_relacao_b(solucao)
dicionario_global

{0: 's',
 1: 't',
 2: 'u',
 3: 'v',
 4: 'w',
 5: 'x',
 6: 'y',
 7: 'z',
 8: 'a',
 9: 'b',
 10: 'c',
 11: 'd',
 12: 'e',
 13: 'f',
 14: 'g',
 15: 'h',
 16: 'i',
 17: 'j',
 18: 'k',
 19: 'l',
 20: 'm',
 21: 'n',
 22: 'o',
 23: 'p',
 24: 'q',
 25: 'r',
 26: 's_'}

In [41]:
import pandas as pd
def substitui_para_letras(solucao,dicionario):
    n_lin, n_col = solucao.shape

    df_solucao = pd.DataFrame(solucao , columns = [i for i in range(n_col)])
    
    for col in df_solucao.columns:
        df_solucao[col] = df_solucao[col].astype(int)
        df_solucao[col] = df_solucao[col].map( dicionario ).astype(str)
        solucao = df_solucao.to_numpy()
    
    return solucao

In [42]:
solucao = candidatos_solucoes[0]
solucao

array([[1.],
       [1.],
       [1.],
       [2.]])

In [43]:
solucao = substitui_para_letras(solucao, dicionario_global)
solucao

array([['t'],
       ['t'],
       ['t'],
       ['u']], dtype=object)

In [44]:
for num, solucao in enumerate(candidatos_solucoes):
    solucao = substitui_para_letras(solucao, dicionario_global)
    candidatos_solucoes[num] = solucao
candidatos_solucoes

[array([['t'],
        ['t'],
        ['t'],
        ['u']], dtype=object),
 array([['t', 't'],
        ['t', 't'],
        ['t', 't'],
        ['u', 'u']], dtype=object),
 array([['t', 't', 't'],
        ['t', 't', 't'],
        ['t', 't', 't'],
        ['u', 'u', 'u']], dtype=object),
 array([['t', 't', 't', 't'],
        ['t', 't', 't', 't'],
        ['t', 't', 't', 't'],
        ['u', 'u', 'u', 'u']], dtype=object),
 array([['t'],
        ['n'],
        ['o'],
        ['u']], dtype=object),
 array([['t', 't'],
        ['n', 'n'],
        ['o', 'o'],
        ['u', 'u']], dtype=object),
 array([['t', 't', 't'],
        ['n', 'n', 'n'],
        ['o', 'o', 'o'],
        ['u', 'u', 'u']], dtype=object),
 array([['t', 't', 't', 't'],
        ['n', 'n', 'n', 'n'],
        ['o', 'o', 'o', 'o'],
        ['u', 'u', 'u', 'u']], dtype=object),
 array([['t'],
        ['t'],
        ['t'],
        ['u']], dtype=object),
 array([['t', 't'],
        ['t', 't'],
        ['t', 't'],
        ['u', 'u

In [45]:
for num_sol, solucao in enumerate(candidatos_solucoes):
    contador_match = 0
    letras_match = ''
    
    for letra in 'tibia':
        if letra in solucao:
            contador_match = contador_match+1
            letras_match = letras_match + ' ' + letra
            
    prop_match = contador_match / len('tibia') *100
    print("Solução = {} - Letras_Match = {} - Matches = {}% ".format(num_sol,letras_match,prop_match))

Solução = 0 - Letras_Match =  t - Matches = 20.0% 
Solução = 1 - Letras_Match =  t - Matches = 20.0% 
Solução = 2 - Letras_Match =  t - Matches = 20.0% 
Solução = 3 - Letras_Match =  t - Matches = 20.0% 
Solução = 4 - Letras_Match =  t - Matches = 20.0% 
Solução = 5 - Letras_Match =  t - Matches = 20.0% 
Solução = 6 - Letras_Match =  t - Matches = 20.0% 
Solução = 7 - Letras_Match =  t - Matches = 20.0% 
Solução = 8 - Letras_Match =  t - Matches = 20.0% 
Solução = 9 - Letras_Match =  t - Matches = 20.0% 
Solução = 10 - Letras_Match =  t - Matches = 20.0% 
Solução = 11 - Letras_Match =  t - Matches = 20.0% 
Solução = 12 - Letras_Match =  t b a - Matches = 60.0% 
Solução = 13 - Letras_Match =  t b a - Matches = 60.0% 
Solução = 14 - Letras_Match =  t b a - Matches = 60.0% 
Solução = 15 - Letras_Match =  t b a - Matches = 60.0% 


In [50]:
candidatos_solucoes[12]

array([['t'],
       ['a'],
       ['w'],
       ['b']], dtype=object)

## Pista 1+1: = 1,13,49,94

Parecem elementos de progressão veremos qual a raiz dessa progressão (se é que existe uma)

In [137]:
for k in range(1,90):
    L = [1,13,49,94]
    
    ###decimais L por K:
    decimais_originais = [i/k%1 for i in L]
    
    ## subtrai o max de todos (para checar se a matriz 0,0,0,0 ocorre (todos elementos sao iguais))
    decimais = np.array(decimais_originais).max() - np.array(decimais_originais)
    
    max_lista = decimais.max()
    
    ## os valores unicos são iguais?
    
    print(k,max_lista)

1 0.0
2 0.5
3 1.1657341758564144e-15
4 0.25
5 0.6000000000000008
6 0.5
7 0.8571428571428572
8 0.625
9 0.33333333333333354
10 0.8000000000000004
11 0.45454545454545403
12 0.75
13 0.7692307692307692
14 0.8571428571428572
15 0.8
16 0.8125
17 0.8235294117647058
18 0.6666666666666667
19 0.8947368421052635
20 0.6500000000000001
21 0.5714285714285714
22 0.5454545454545455
23 0.5217391304347826
24 0.875
25 0.9199999999999999
26 0.8461538461538461
27 0.7777777777777779
28 0.7142857142857143
29 0.6551724137931035
30 0.6
31 0.5483870967741935
32 0.90625
33 0.8181818181818183
34 0.7352941176470588
35 0.6571428571428569
36 0.5833333333333334
37 0.5135135135135134
38 0.44736842105263175
39 0.38461538461538447
40 0.32500000000000007
41 0.2926829268292683
42 0.2857142857142857
43 0.27906976744186046
44 0.27272727272727276
45 0.26666666666666666
46 0.2608695652173913
47 0.2765957446808511
48 0.9375
49 0.9183673469387754
50 0.96
51 0.9411764705882353
52 0.923076923076923
53 0.9056603773584906
54 0.88888

Candidatos á raiz: 3

1 * 3*n = 1,13,49,94 onde 
n assume um valor inteiro

para 
- n = 0 temos:   1 * 3 * 0 = 1
- n = 3 temos:   1 * 3 * 3 = 13
- n = 16 temos:   1 * 3 * 3 = 49
- n = 31 temos:   1 * 3 * 31 = 94